"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR.parent, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Читаем из окружения. В dev (Codespace, без .env) — небезопасный дефолт для удобства;
# в бою значение задаётся переменной SECRET_KEY в панели Amvera (в git его нет).
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure---z%y3#k#jja)@qez$n2)pm0$&qnl0qf_3(#3yu!5@0mj*)n)%",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Читаем из окружения. В dev (Codespace, без .env) — дефолт True для удобства
# (подробные ошибки, раздача статики/media через runserver); в бою на Amvera
# ОБЯЗАТЕЛЬНО задать переменную DEBUG=False. Строку из env разбираем явно, иначе
# "False" (непустая строка) молча стало бы истиной.
DEBUG = os.getenv("DEBUG", "True").strip().lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
CSRF_TRUSTED_ORIGINS = []

# Dev: автоматически разрешаем forwarded-домен GitHub Codespaces.
# Срабатывает только внутри Codespaces (есть переменная CODESPACE_NAME),
# на проде/локально поведение не меняется.
_codespace = os.getenv("CODESPACE_NAME")
if _codespace:
    _domain = os.getenv("GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN", "app.github.dev")
    _host = f"{_codespace}-8000.{_domain}"
    ALLOWED_HOSTS.append(_host)
    CSRF_TRUSTED_ORIGINS.append(f"https://{_host}")

# Бой: боевые хосты backend задаются переменной DJANGO_ALLOWED_HOSTS (список через
# запятую), чтобы вписать поддомен Amvera / свой .ru без правки кода. Для каждого
# хоста добавляем https-origin в CSRF_TRUSTED_ORIGINS. В dev переменной нет — блок
# ничего не делает.
for _h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(","):
    _h = _h.strip()
    if _h:
        ALLOWED_HOSTS.append(_h)
        CSRF_TRUSTED_ORIGINS.append(f"https://{_h}")

CORS_ALLOW_ALL_ORIGINS = True
# Разрешаем кастомный заголовок гостевой корзины (X-Cart-Token) в дополнение к
# стандартному списку django-cors-headers. Без этого браузер блокирует preflight
# любого запроса корзины, несущего токен (см. frontend/_scratch/PLAN_STEP_4.md).
CORS_ALLOW_HEADERS = [*default_headers, "x-cart-token"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

        # сторонние
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    'mptt',

    # наши
    'apps.users',
    'apps.catalog',
    'apps.cart',
    'apps.core',
    'apps.orders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # должно быть первым
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "GardenGram API",
    "DESCRIPTION": "API for GardenGram project",
    "VERSION": "1.0.0",
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "SECURITY": [{"BearerAuth": []}],
    # Один и тот же набор способов доставки используется в нескольких полях (заказ, превью) —
    # задаём enum явное имя, чтобы схема была однозначной.
    "ENUM_NAME_OVERRIDES": {
        "DeliveryMethodEnum": "apps.core.models.DeliveryMethod",
    },
}

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "gardengram"),
        "USER": os.getenv("POSTGRES_USER", "gg_user"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "gg_password"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),  # имя сервиса из docker-compose
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Asia/Yekaterinburg"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Медиа-файлы (загружаемые фото товаров).
# В dev раздаются Django через config/urls.py при DEBUG; папка media/ — в .gitignore.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Кастомная модель пользователя (вход по телефону).
# Задаётся ДО первой миграции — менять после наполнения базы крайне болезненно.
AUTH_USER_MODEL = "users.User"
