# Generated by Django 5.2.15 on 2026-06-23 06:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_delivery_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3000"),
                        help_text="От этой суммы товаров доставка по Иглино бесплатна.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Порог бесплатной доставки, ₽",
                    ),
                ),
                (
                    "local_delivery_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("300"),
                        help_text="Берётся, если сумма товаров меньше порога бесплатной доставки.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Стоимость доставки по Иглино, ₽",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки магазина",
                "verbose_name_plural": "Настройки магазина",
            },
        ),
    ]
