# Generated by Django 5.2.15 on 2026-06-23 06:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        help_text="Читаемый номер для покупателя и владельца (GG-ГГММДД-XXXX).",
                        max_length=20,
                        unique=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "access_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Секретный ключ: по нему гость открывает свой заказ без аккаунта.",
                        unique=True,
                        verbose_name="Токен доступа",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=255, verbose_name="Имя покупателя"),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Телефон должен быть в формате +7XXXXXXXXXX (10 цифр после +7).",
                                regex="^\\+7\\d{10}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("PICKUP", "Самовывоз"),
                            ("LOCAL", "Доставка по Иглино"),
                        ],
                        default="PICKUP",
                        max_length=10,
                        verbose_name="Способ доставки",
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True,
                        help_text="Обязателен при доставке; при самовывозе пусто.",
                        verbose_name="Адрес доставки",
                    ),
                ),
                (
                    "wanted_time",
                    models.CharField(
                        blank=True,
                        help_text="Свободный текст, например «после 18:00 в будни».",
                        max_length=255,
                        verbose_name="Желаемое время приезда",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий покупателя"),
                ),
                (
                    "goods_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма товаров, ₽"
                    ),
                ),
                (
                    "delivery_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Стоимость доставки, ₽",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Итого, ₽"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новый"),
                            ("ASSEMBLED", "Собран"),
                            ("ISSUED", "Выдан"),
                            ("CANCELLED", "Отменён"),
                        ],
                        default="NEW",
                        max_length=12,
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("UNPAID", "Не оплачен"), ("PAID", "Оплачен")],
                        default="UNPAID",
                        help_text="Задел под будущую оплату. Пока переключается вручную.",
                        max_length=8,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Название товара"),
                ),
                (
                    "variant_label",
                    models.CharField(max_length=255, verbose_name="Форма продажи"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Замороженная цена варианта на момент оформления заказа.",
                        max_digits=10,
                        verbose_name="Цена за шт., ₽",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.productvariant",
                        verbose_name="Вариант товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказа",
                "ordering": ["id"],
            },
        ),
    ]
