# Generated by Django 5.2.15 on 2026-06-16 09:10

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Для будущих ЧПУ-ссылок. Можно оставить пустым.",
                        max_length=255,
                        verbose_name="Slug (для ссылок)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть ветку из каталога.",
                        verbose_name="Активна",
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        help_text="Пусто = категория верхнего уровня (корень дерева).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PLANT", "Растение"),
                            ("SUPPLY", "Сопутствующий товар"),
                        ],
                        default="PLANT",
                        help_text="Растение или сопутствующий товар. Влияет на набор полей варианта.",
                        max_length=10,
                        verbose_name="Тип товара",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, verbose_name="Название (рус.)"),
                ),
                (
                    "cultivar",
                    models.CharField(
                        blank=True,
                        help_text="Необязательно. Есть не у всех позиций; нужен для будущей фильтрации.",
                        max_length=255,
                        verbose_name="Сорт",
                    ),
                ),
                (
                    "name_lat",
                    models.CharField(
                        blank=True,
                        help_text="Необязательно. Если заполнено — показывается как «Русское (Латинское)».",
                        max_length=255,
                        verbose_name="Латинское название",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Черновик не виден в каталоге. Можно завести карточку и дозалить фото позже.",
                        verbose_name="Опубликован",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "category",
                    mptt.fields.TreeForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Продавец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name_ru"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/%Y/%m/", verbose_name="Фото"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Меньшее число = выше. Первое фото считается главным.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        help_text="Необязательно. Текст для доступности и SEO на будущем фронте.",
                        max_length=255,
                        verbose_name="Подпись (alt)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото товара",
                "verbose_name_plural": "Фото товара",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за шт., ₽"
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "В наличии"),
                            ("OUT_OF_STOCK", "Нет в наличии"),
                        ],
                        default="IN_STOCK",
                        help_text="Главный источник правды о наличии. Товар не скрывается при отсутствии — показывается со статусом «Нет в наличии».",
                        max_length=20,
                        verbose_name="Наличие",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Необязательно. Точное число известно не всегда; наличием управляет статус.",
                        null=True,
                        verbose_name="Количество (опц.)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы скрыть вариант, не удаляя его.",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "variant_label",
                    models.CharField(
                        blank=True,
                        help_text="Необязательно. Если пусто — подпись можно собрать из полей формы продажи.",
                        max_length=255,
                        verbose_name="Подпись варианта",
                    ),
                ),
                (
                    "root_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OKS", "ОКС (открытая, без горшка)"),
                            ("ZKS", "ЗКС (закрытая, в контейнере)"),
                        ],
                        help_text="Только для растений. Для сопутствующих товаров оставьте пустым.",
                        max_length=3,
                        verbose_name="Корневая система",
                    ),
                ),
                (
                    "volume_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Объём в литрах: горшок ЗКС у растения или фасовка (мешок) у грунта/торфа.",
                        max_digits=6,
                        null=True,
                        verbose_name="Объём, л",
                    ),
                ),
                (
                    "size_label",
                    models.CharField(
                        blank=True,
                        help_text="Размер, не выражаемый литрами: диаметр горшка «P9», «50 кг» и т.п.",
                        max_length=100,
                        verbose_name="Размер (текст)",
                    ),
                ),
                (
                    "age_note",
                    models.CharField(
                        blank=True,
                        help_text="Только для растений. Справочно; на цену влияет слабо.",
                        max_length=255,
                        verbose_name="Возраст (заметка)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант товара",
                "verbose_name_plural": "Варианты товара",
                "ordering": ["price"],
            },
        ),
    ]
