# Generated by Django 5.1.2 on 2024-10-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
